### ISSUE TITLE
install error, RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by sevenguin** [pwaller/pyprof2calltree#22]
when i use `pip install pyprof2calltree`, the following error occurred(**Ubuntu x86_64, and pyprof2calltree=1.4.3**):

```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dkeZX1/pyprof2calltree/setup.py", line 44, in <module>
        'pyprof2calltree = pyprof2calltree:main',
      File "/local/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/local/anaconda2/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 580, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 825, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 837, in obtain
        return installer(requirement)
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 272, in fetch_build_egg
        dist = self.__class__({'script_args':['easy_install']})
      File "/local/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
......(repeat error)
RuntimeError: maximum recursion depth exceeded
```

**Comment by pwaller** [comment]
This doesn't look like a problem with pyprof2calltree but instead a problem with distribute and/or your environment.

As far as I understand it, `distribute` is now deprecated for a long time and replaced by `setuptools`. See the note about that here: https://pypi.python.org/pypi/distribute/0.6.49. The most recent version of distribute simply installs setuptools: https://pypi.python.org/pypi/distribute/0.7.3

Please try updating `pip`, `setuptools` and `distribute` (or remove it) to the latest versions and try again.

**Comment by sevenguin** [comment]
yeah, it's my problem, sorry to trouble you, and thanks for your suggestion.
